// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Avatar: typeof import('primevue/avatar')['default']
    BaseDateFormat: typeof import('./components/base/BaseDateFormat.vue')['default']
    BaseInputGrid: typeof import('./components/base/BaseInputGrid.vue')['default']
    BaseInputGroup: typeof import('./components/base/BaseInputGroup.vue')['default']
    BasePage: typeof import('./components/base/BasePage.vue')['default']
    BasePageHeader: typeof import('./components/base/BasePageHeader.vue')['default']
    Breadcrumb: typeof import('primevue/breadcrumb')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    Column: typeof import('primevue/column')['default']
    DataTable: typeof import('primevue/datatable')['default']
    InputSwitch: typeof import('primevue/inputswitch')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Menu: typeof import('primevue/menu')['default']
    MenuList: typeof import('./components/site/MenuList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('primevue/sidebar')['default']
    SiteHeader: typeof import('./components/site/SiteHeader.vue')['default']
    SiteSidebar: typeof import('./components/site/SiteSidebar.vue')['default']
    SpinnerIcon: typeof import('./components/base/SpinnerIcon.vue')['default']
  }
}

export {}
