// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Avatar: typeof import('primevue/avatar')['default']
    Badge: typeof import('primevue/badge')['default']
    BaseDateFormat: typeof import('./components/base/BaseDateFormat.vue')['default']
    BaseDropZone: typeof import('./components/base/base-file-uploader/BaseDropZone.vue')['default']
    BaseEditor: typeof import('./components/base/base-editor/BaseEditor.vue')['default']
    BaseEmptyPlaceholder: typeof import('./components/base/BaseEmptyPlaceholder.vue')['default']
    BaseFilePreview: typeof import('./components/base/base-file-uploader/BaseFilePreview.vue')['default']
    BaseInputGrid: typeof import('./components/base/BaseInputGrid.vue')['default']
    BaseInputGroup: typeof import('./components/base/BaseInputGroup.vue')['default']
    BasePage: typeof import('./components/base/BasePage.vue')['default']
    BasePageHeader: typeof import('./components/base/BasePageHeader.vue')['default']
    BoldIcon: typeof import('./components/base/base-editor/icons/BoldIcon.vue')['default']
    Breadcrumb: typeof import('primevue/breadcrumb')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    CodeBlockIcon: typeof import('./components/base/base-editor/icons/CodeBlockIcon.vue')['default']
    CodingIcon: typeof import('./components/base/base-editor/icons/CodingIcon.vue')['default']
    Column: typeof import('primevue/column')['default']
    DashboardStats: typeof import('./components/base/DashboardStats.vue')['default']
    DataTable: typeof import('primevue/datatable')['default']
    InputSwitch: typeof import('primevue/inputswitch')['default']
    InputText: typeof import('primevue/inputtext')['default']
    ItalicIcon: typeof import('./components/base/base-editor/icons/ItalicIcon.vue')['default']
    LineChart: typeof import('./components/base/LineChart.vue')['default']
    ListIcon: typeof import('./components/base/base-editor/icons/ListIcon.vue')['default']
    ListUlIcon: typeof import('./components/base/base-editor/icons/ListUlIcon.vue')['default']
    LogoBlack: typeof import('./components/site/LogoBlack.vue')['default']
    LogoWhite: typeof import('./components/site/LogoWhite.vue')['default']
    MainLogo: typeof import('./components/site/MainLogo.vue')['default']
    Menu: typeof import('primevue/menu')['default']
    MenuCenterIcon: typeof import('./components/base/base-editor/icons/MenuCenterIcon.vue')['default']
    MenuList: typeof import('./components/site/MenuList.vue')['default']
    ParagraphIcon: typeof import('./components/base/base-editor/icons/ParagraphIcon.vue')['default']
    QuoteIcon: typeof import('./components/base/base-editor/icons/QuoteIcon.vue')['default']
    RedoIcon: typeof import('./components/base/base-editor/icons/RedoIcon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('primevue/sidebar')['default']
    SiteHeader: typeof import('./components/site/SiteHeader.vue')['default']
    SiteSidebar: typeof import('./components/site/SiteSidebar.vue')['default']
    SpinnerIcon: typeof import('./components/base/SpinnerIcon.vue')['default']
    StrikethroughIcon: typeof import('./components/base/base-editor/icons/StrikethroughIcon.vue')['default']
    UnderlineIcon: typeof import('./components/base/base-editor/icons/UnderlineIcon.vue')['default']
    UndoIcon: typeof import('./components/base/base-editor/icons/UndoIcon.vue')['default']
  }
}

export {}
