// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseInputGrid: typeof import('./components/base/BaseInputGrid.vue')['default']
    BaseInputGroup: typeof import('./components/base/BaseInputGroup.vue')['default']
    BasePage: typeof import('./components/base/BasePage.vue')['default']
    BasePageHeader: typeof import('./components/base/BasePageHeader.vue')['default']
    MenuList: typeof import('./components/site/MenuList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SiteHeader: typeof import('./components/site/SiteHeader.vue')['default']
    SiteSidebar: typeof import('./components/site/SiteSidebar.vue')['default']
    SpinnerIcon: typeof import('./components/base/SpinnerIcon.vue')['default']
  }
}

export {}
